name: ManipulateVolumeObject
version: 0.1
author: Naioku
main: pl.adrian_komuda.manipulate_volume_object.Main
description: Copying, deleting (etc.) volume objects.
api-version: 1.18

commands:
  command1:
    description: Example command.